import type { Manifest, SurvivalAnalysis } from "./types";
import { ENDPOINTS } from "./types";
import { groupingLabel } from "./grouping";
import cohortPapers from "./cohort-citations.json";
import releases from "./citation-releases.json";
import { SOFTWARE_VERSION } from "./version";

export interface CitationRecord {
  id: string;
  role: string;
  authors: string[];
  title: string;
  year?: number;
  journal?: string;
  volume?: string;
  issue?: string;
  pages?: string;
  doi?: string;
  url: string;
}
export interface AnalysisProvenance {
  version: 1;
  program: "TCGA" | "CPTAC";
  project: string;
  cohort: string;
  dataVersion: string;
  softwareVersion: string;
  upstreamRelease: string | null;
  assetDataVersion: string | null;
  expressionSource: string;
  survivalSource: string;
  citations: CitationRecord[];
  acknowledgement: string;
  cohortPublicationNote: string;
}
const gdc: CitationRecord = {
  id: "heath2021gdc",
  role: "Data repository",
  authors: ["Heath, A. P.", "Ferretti, V.", "Agrawal, S.", "others"],
  title: "The NCI Genomic Data Commons",
  year: 2021,
  journal: "Nature Genetics",
  volume: "53",
  pages: "257–262",
  doi: "10.1038/s41588-021-00791-5",
  url: "https://doi.org/10.1038/s41588-021-00791-5",
};
const xena: CitationRecord = {
  id: "goldman2020xena",
  role: "Expression and clinical data distribution",
  authors: ["Goldman, M. J.", "Craft, B.", "Hastie, M.", "others"],
  title:
    "Visualizing and interpreting cancer genomics data via the Xena platform",
  year: 2020,
  journal: "Nature Biotechnology",
  volume: "38",
  pages: "675–678",
  doi: "10.1038/s41587-020-0546-8",
  url: "https://doi.org/10.1038/s41587-020-0546-8",
};
const cdr: CitationRecord = {
  id: "liu2018cdr",
  role: "TCGA clinical outcomes",
  authors: ["Liu, J.", "Lichtenberg, T.", "Hoadley, K. A.", "others"],
  title:
    "An Integrated TCGA Pan-Cancer Clinical Data Resource to Drive High-Quality Survival Outcome Analytics",
  year: 2018,
  journal: "Cell",
  volume: "173",
  issue: "2",
  pages: "400–416.e11",
  doi: "10.1016/j.cell.2018.02.052",
  url: "https://doi.org/10.1016/j.cell.2018.02.052",
};
export function resolveProvenance(
  analysis: SurvivalAnalysis,
  manifest?: Manifest | null,
): AnalysisProvenance {
  const cohort = analysis.cohort,
    program = cohort.startsWith("CPTAC-") ? "CPTAC" : "TCGA";
  const project =
    program === "CPTAC" ? "CPTAC-3" : `TCGA-${cohort.replace(/^TCGA-/, "")}`;
  const record =
    manifest?.data_version === analysis.dataVersion
      ? manifest.cohorts[cohort]
      : undefined;
  const known = (
    releases as Record<
      string,
      Record<
        string,
        { upstreamRelease: string | null; assetDataVersion: string | null }
      >
    >
  )[analysis.dataVersion]?.[cohort];
  const upstreamRelease =
    record?.source?.gdc_release?.data_release ?? known?.upstreamRelease ?? null;
  const assetDataVersion =
    record?.reused_from?.data_version ?? known?.assetDataVersion ?? null;
  const original =
    (cohortPapers as Record<string, CitationRecord[]>)[cohort] ?? [];
  const citations: CitationRecord[] = [
    {
      id: project.toLowerCase(),
      role: "Source dataset",
      authors: ["National Cancer Institute"],
      title:
        program === "TCGA"
          ? `The Cancer Genome Atlas: ${project}`
          : "Clinical Proteomic Tumor Analysis Consortium, CPTAC-3 (phs001287)",
      url: `https://portal.gdc.cancer.gov/projects/${project}`,
    },
    gdc,
    ...(program === "TCGA"
      ? [xena, cdr]
      : [
          {
            id: "gdc-survival",
            role: "Overall-survival source documentation",
            authors: ["National Cancer Institute"],
            title: "GDC API: Data Analysis — Survival Analysis",
            url: "https://docs.gdc.cancer.gov/API/Users_Guide/Data_Analysis/",
          },
        ]),
    ...original,
    {
      id: "survscope",
      role: "Analysis software",
      authors: ["Li, Yaoxiang"],
      title: `SurvScope ${SOFTWARE_VERSION}`,
      url: "https://github.com/oncologylab/survscope",
    },
  ];
  return {
    version: 1,
    program,
    project,
    cohort,
    dataVersion: analysis.dataVersion,
    softwareVersion: SOFTWARE_VERSION,
    upstreamRelease,
    assetDataVersion,
    expressionSource: analysis.sourceExpression,
    survivalSource: analysis.sourceSurvival,
    citations,
    acknowledgement:
      program === "TCGA"
        ? "The results shown here are in whole or part based upon data generated by the TCGA Research Network: https://www.cancer.gov/tcga."
        : "Data used in this publication were generated by the National Cancer Institute Clinical Proteomic Tumor Analysis Consortium (CPTAC).",
    cohortPublicationNote: original.length
      ? "Cohort-associated publications are listed below. SurvScope uses the eligible patients in its recorded data snapshot; this subset can differ from the publication cohort."
      : "No cohort-specific publication has been verified for this classification. Cite the source dataset and resource references below.",
  };
}
export function attachProvenance(
  analysis: SurvivalAnalysis,
  manifest?: Manifest | null,
): SurvivalAnalysis {
  return { ...analysis, provenance: resolveProvenance(analysis, manifest) };
}
export function citationText(c: CitationRecord): string {
  const authors = c.authors
    .map((a) => (a === "others" ? "et al." : a))
    .join(", ")
    .replace(/\.$/, "");
  return `${authors}. ${c.title}.${c.journal ? ` ${c.journal}.` : ""}${c.year ? ` ${c.year}` : ""}${c.volume ? `;${c.volume}` : ""}${c.issue ? `(${c.issue})` : ""}${c.pages ? `:${c.pages}` : ""}${c.year || c.volume ? "." : ""} ${c.doi ? `https://doi.org/${c.doi}` : c.url}`;
}
export function methodsText(a: SurvivalAnalysis): string {
  const p = a.provenance ?? resolveProvenance(a);
  const outcomes = ENDPOINTS.filter(
    (ep) => a.endpoints[ep].quality !== "unavailable",
  )
    .map((ep) => {
      const e = a.endpoints[ep];
      return `${ep}: ${e.nLow} lower-expression and ${e.nHigh} higher-expression patients (${e.eventsLow} and ${e.eventsHigh} events); ${e.excludedMiddle} middle patients excluded from ${e.eligibleN} patients with eligible data`;
    })
    .join(". ");
  return `${a.gene} (${a.ensembl}) RNA expression was analyzed in ${p.project}, ${a.cohortLabel} (${a.cohort}), using SurvScope ${p.softwareVersion} and data release ${a.dataVersion}. Expression: ${p.expressionSource}; outcomes: ${p.survivalSource}. Upstream GDC release: ${p.upstreamRelease ?? "not recorded"}.${p.assetDataVersion ? ` Cohort assets originated in SurvScope data ${p.assetDataVersion}.` : ""} Grouping: ${groupingLabel(a.grouping)}. Grouping uses patients with available expression and endpoint follow-up; ties are retained together, with exact reference grouping for the median. ${outcomes}. Kaplan–Meier estimates, a two-sided log-rank test, and an unadjusted Cox model with Breslow ties were used. Hazard ratios compare higher with lower expression. Benjamini–Hochberg q-values cover the available outcomes for this analysis. ${p.acknowledgement}`;
}
const bibEscape = (s: string) =>
  s
    .replace(/\\/g, "\\textbackslash{}")
    .replace(/[{}%&#_$]/g, (c) => `\\${c}`)
    .replace(/\r?\n/g, " ");
export function bibliography(
  a: SurvivalAnalysis,
  kind: "text" | "bibtex" | "ris",
): string {
  const p = a.provenance ?? resolveProvenance(a),
    release = `SurvScope data ${a.dataVersion}; upstream GDC ${p.upstreamRelease ?? "not recorded"}; cohort ${a.cohort}`;
  if (kind === "text")
    return `${release}\n\n${p.citations.map(citationText).join("\n\n")}\n\n${p.acknowledgement}\n`;
  if (kind === "bibtex")
    return (
      p.citations
        .map(
          (c) =>
            `@${c.journal ? "article" : "misc"}{${c.id},\n${Object.entries({
              author: c.authors
                .map((a) =>
                  a === "others"
                    ? "others"
                    : a.includes(",")
                      ? bibEscape(a)
                      : `{${bibEscape(a)}}`,
                )
                .join(" and "),
              title: bibEscape(c.title),
              year: c.year,
              journal: c.journal,
              volume: c.volume,
              number: c.issue,
              pages: c.pages?.replaceAll("–", "--"),
              doi: c.doi,
              url: c.url,
              note: release,
            })
              .filter(([, v]) => v !== undefined)
              .map(
                ([k, v]) =>
                  `  ${k} = {${k === "title" || k === "author" ? v : bibEscape(String(v))}}`,
              )
              .join(",\n")}\n}`,
        )
        .join("\n\n") + "\n"
    );
  return (
    p.citations
      .map((c) =>
        [
          "TY  - " + (c.journal ? "JOUR" : "GEN"),
          ...c.authors.map((a) => "AU  - " + (a === "others" ? "et al." : a)),
          `TI  - ${c.title}`,
          ...Object.entries({
            PY: c.year,
            JO: c.journal,
            VL: c.volume,
            IS: c.issue,
            SP: c.pages?.split("–")[0],
            EP: c.pages?.split("–")[1],
            DO: c.doi,
            UR: c.url,
            N1: release,
          })
            .filter(([, v]) => v !== undefined)
            .map(([k, v]) => `${k}  - ${String(v).replace(/\r?\n/g, " ")}`),
          "ER  -",
        ].join("\n"),
      )
      .join("\n\n") + "\n"
  );
}
